#!/bin/bash

RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'
CYAN=$'\033[0;36m'
NC=$'\033[0m' # No Color

SCAN_MODE="PENETRATION"
NMAP_PHASE1_OPTS="-Pn -sS -T3 -p-"

if[ "$1" == "--ctf"]; then
    SCAN_MODE="CTF"
    NMAP_PHASE1_OPTS="-Pn -sS -T4 -p- --min-rate 1000 --max-retries 1"
fi

print_banner() {
cat << EOF
${CYAN}
                                                                                                                  
                                                                                                                  
RRRRRRRRRRRRRRRRR                                                                                   888888888     
R::::::::::::::::R                                                                                88:::::::::88   
R::::::RRRRRR:::::R                                                                             88:::::::::::::88 
RR:::::R     R:::::R                                                                           8::::::88888::::::8
  R::::R     R:::::R    eeeeeeeeeeee        cccccccccccccccc   ooooooooooo   nnnn  nnnnnnnn    8:::::8     8:::::8
  R::::R     R:::::R  ee::::::::::::ee    cc:::::::::::::::c oo:::::::::::oo n:::nn::::::::nn  8:::::8     8:::::8
  R::::RRRRRR:::::R  e::::::eeeee:::::ee c:::::::::::::::::co:::::::::::::::on::::::::::::::nn  8:::::88888:::::8 
  R:::::::::::::RR  e::::::e     e:::::ec:::::::cccccc:::::co:::::ooooo:::::onn:::::::::::::::n  8:::::::::::::8  
  R::::RRRRRR:::::R e:::::::eeeee::::::ec::::::c     ccccccco::::o     o::::o  n:::::nnnn:::::n 8:::::88888:::::8 
  R::::R     R:::::Re:::::::::::::::::e c:::::c             o::::o     o::::o  n::::n    n::::n8:::::8     8:::::8
  R::::R     R:::::Re::::::eeeeeeeeeee  c:::::c             o::::o     o::::o  n::::n    n::::n8:::::8     8:::::8
  R::::R     R:::::Re:::::::e           c::::::c     ccccccco::::o     o::::o  n::::n    n::::n8:::::8     8:::::8
RR:::::R     R:::::Re::::::::e          c:::::::cccccc:::::co:::::ooooo:::::o  n::::n    n::::n8::::::88888::::::8
R::::::R     R:::::R e::::::::eeeeeeee   c:::::::::::::::::co:::::::::::::::o  n::::n    n::::n 88:::::::::::::88 
R::::::R     R:::::R  ee:::::::::::::e    cc:::::::::::::::c oo:::::::::::oo   n::::n    n::::n   88:::::::::88   
RRRRRRRR     RRRRRRR    eeeeeeeeeeeeee      cccccccccccccccc   ooooooooooo     nnnnnn    nnnnnn     888888888     

${NC}${YELLOW}
                                        [*] Author  : 8omp                                                                  
                                        [*] Version : 1.0.2
                                        [*] Github  : https://github.com/8omp/recon8.git ${NC}${RED}
                                        [!] WARNING : Use ONLY on authorized targets. ${NC}


EOF
}

print_banner

echo -e "${YELLOW}[*] Scan mode: $SCAN_MODE${NC}"
if [ "$SCAN_MODE" == "CTF"]; then
echo -e "${RED}[!] Aggressive scanning enabled.${NC}"
fi

echo -n -e "${GREEN}[>] Enter the target domain or IP address: ${NC}"
read TARGET_IP

if [ -z "$TARGET_IP" ]; then
    echo -e "${RED}[-] No domain or IP address entered. Exiting.${NC}"
    exit 1
fi


# nmap phase1: found open ports
echo ""
echo -e "${YELLOW}[*] Starting nmap on $TARGET_IP...${NC}"

PHASE1_LOG_FILE="nmap-phase1_${TARGET_IP}.txt"
echo "--------------------------------------------------------------------------------"

sudo nmap $NMAP_PHASE1_OPTS "$TARGET_IP" -oN "$PHASE1_LOG_FILE"

echo "--------------------------------------------------------------------------------"

TARGET_PORTS=$(grep -E "^[0-9]+/tcp[[:space:]]+open" "$PHASE1_LOG_FILE" | cut -d '/' -f 1 | tr '\n' ',' | sed 's/,$//')

echo ""
if [ -z "$TARGET_PORTS" ]; then
    echo -e "${RED}[-] No open ports found on $TARGET_IP.${NC}"
    exit 1
else
    echo -e "${GREEN}[+] Open ports found: $TARGET_PORTS${NC}"
fi

# nmap phase2: service enumeration
PHASE2_LOG_FILE="nmap-phase2_${TARGET_IP}.txt"
echo ""
echo "--------------------------------------------------------------------------------"

sudo nmap -Pn -sC -sV -T4 -p "$TARGET_PORTS" "$TARGET_IP" -oN "$PHASE2_LOG_FILE"

echo "--------------------------------------------------------------------------------"
